### ISSUE TITLE
mac下安装openvpn

### ISSUE THREAD

**Issue by zackzhangkai** [zackzhangkai/shadowsocks#2]
~ 参考该篇博客： https://blog.csdn.net/woshishui50/article/details/50490435  ~
+ 下载  Mac下的免费软件 [Tunnelblick](https://www.tunnelblick.net)
+ 安装成功后，可以选择新建和导入vpn提供商给予的证书，后缀是 .ovpn

**Comment by kaizamm** [comment]
```
echo 1 > /proc/sys/net/ipv4/ip_forward
sed -i '/net.ipv4.ip_forward/s/0/1/' /etc/sysctl.conf 
 sysctl -p
```
